// Excuse list for excuse module

excuse = [
"clock speed",
"solar flares",
"electromagnetic radiation from satellite debris",
"static from nylon underwear",
"static from plastic slide rules",
"global warming",
"poor power conditioning",
"static buildup",
"doppler effect",
"hardware stress fractures",
"magnetic interference from money/credit cards",
"dry joints on cable plug",
"we're waiting for [the phone company] to fix that line",
"sounds like a Windows problem, try calling Microsoft support",
"temporary routing anomaly",
"somebody was calculating pi on the server",
"fat electrons in the lines",
"excess surge protection",
"floating point processor overflow",
"divide-by-zero error",
"POSIX compliance problem",
"monitor resolution too high",
"improperly oriented keyboard",
"network packets travelling uphill (use a carrier pigeon)",
"Decreasing electron flux",
"first Saturday after first full moon in Winter",
"radiosity depletion",
"CPU radiator broken",
"It works the way the Wang did, what's the problem",
"positron router malfunction",
"cellular telephone interference",
"techtonic stress",
"piezo-electric interference",
"(l)user error",
"working as designed",
"dynamic software linking table corrupted",
"heavy gravity fluctuation, move computer to floor rapidly",
"secretary plugged hairdryer into UPS",
"terrorist activities",
"not enough memory, go get system upgrade",
"interrupt configuration error",
"spaghetti cable cause packet failure",
"boss forgot system password",
"bank holiday - system operating credits  not recharged",
"virus attack, loser responsible",
"waste water tank overflowed onto computer",
"Complete Transient Lockout",
"bad ether in the cables",
"Bogon emissions",
"Change in Earth's rotational speed",
"Cosmic ray particles crashed through the hard disk platter",
"Smell from unhygienic janitorial staff wrecked the tape heads",
"Little hamster in running wheel had coronary; waiting for replacement to be Fedexed from Wyoming",
"Evil dogs hypnotised the night shift",
"Plumber mistook routing panel for decorative wall fixture",
"Electricians made popcorn in the power supply",
"Groundskeepers stole the root password",
"high pressure system failure",
"failed trials, system needs redesigned",
"system has been recalled",
"not approved by the FCC",
"need to wrap system in aluminum foil to fix problem",
"not properly grounded, please bury computer",
"CPU needs recalibration",
"system needs to be rebooted",
"bit bucket overflow",
"descramble code needed from software company",
"only available on a need to know basis",
"knot in cables caused data stream to become twisted and kinked",
"nesting roaches shorted out the ether cable",
"The file system is full of it",
"Satan did it",
"Daemons did it",
"You're out of memory",
"There isn't any problem",
"Unoptimized hard drive",
];