// Fortune list for fortune module

fortune = [ 
"A dream you have will come true.",
"Our deeds determine us, as much as we determine our deeds.",
"Never give up. You're not a failure if you don't give up.",
"You will become great if you believe in yourself.",
"There is no greater pleasure than seeing your loved ones prosper.",
"You will marry your lover.",
"A very attractive person has a message for you.",
"You already know the answer to the questions lingering inside your head.",
"It is now, and in this world, that we must live.",
"You must try, or hate yourself for not trying.",
"You can make your own happiness.",
"The greatest risk is not taking one.",
"The love of your life is stepping into your planet this summer.",
"Love can last a lifetime, if you want it to.",
"Adversity is the parent of virtue.",
"Serious trouble will bypass you.",
"A short stranger will soon enter your life with blessings to share.",
"Now is the time to try something new.",
"Wealth awaits you very soon.",
"If you feel you are right, stand firmly by your convictions.",
"Keep your eye out for someone special.",
"You are very talented in many ways.",
"A stranger, is a friend you have not spoken to yet.",
"A new voyage will fill your life with untold memories.",
"You will travel to many exotic places in your lifetime.",
"Your ability for accomplishment will follow with success.",
"Nothing astonishes men so much as common sense and plain dealing.",
"Its amazing how much good you can do if you don't care who gets the credit.",
"Everyone agrees. You are the best.",
"LIFE CONSISTS NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.",
"Jealousy doesn't open doors, it closes them!",
"It's better to be alone sometimes.",
"When fear hurts you, conquer it and defeat it!",
"Let the deeds speak.",
"You will be called in to fulfill a position of high honor and responsibility.",
"The man on the top of the mountain did not fall there.",
"You will conquer obstacles to achieve success.",
"Joys are often the shadows, cast by sorrows.",
"Fortune favors the brave.",
"An upward movement initiated in time can counteract fate.",
"A journey of a thousand miles begins with a single step.",
"Sometimes you just need to lay on the floor.",
"Never give up. Always find a reason to keep trying.",
"If you have something worth fighting for, then fight for it.",
"Stop wishing. Start doing.",
"Accept your past without regrets. Handle your present with confidence. Face your future without fear.",
"Stay true to those who would do the same for you.",
"Ask yourself if what you are doing today is getting you closer to where you want to be tomorrow.",
"Happiness is an activity.",
"Help is always needed but not always appreciated. Stay true to your heart and help those in need weather they appreciate it or not.",
"Hone your competitive instincts.",
"Finish your work on hand don't be greedy.",
"For success today, look first to yourself.",
"Your fortune is as sweet as a cookie.",
"Integrity is the essence of everything successful.",
"If you're happy, you're successful.",
"You will always be surrounded by true friends",
"Believing that you are beautiful will make you appear beautiful to others around you.",
"Happiness comes from a good life.",
"Before trying to please others think of what makes you happy.",
"When hungry, order more Chinese food.",
"Your golden opportunity is coming shortly.",
"For hate is never conquered by hate. Hate is conquered by love.",
"A beautiful, smart, and loving person will be coming into your life.",
"A dubious friend may be an enemy in camouflage.",
"A feather in the hand is better than a bird in the air.",
"A fresh start will put you on your way.",
"A friend asks only for your time not your money.",
"A friend is a present you give yourself.",
"A gambler not only will lose what he has, but also will lose what he doesn’t have.",
"A golden egg of opportunity falls into your lap this month.",
"A good friendship is often more important than a passionate romance.",
"A good time to finish up old tasks.",
"A hunch is creativity trying to tell you something.",
"A light heart carries you through all the hard times.",
"A new perspective will come with the new year.",
"A person is never to old to learn.",
"A person of words and not deeds is like a garden full of weeds.",
"A pleasant surprise is waiting for you.",
"A smile is your personal welcome mat.",
"A smooth long journey! Great expectations.",
"A soft voice may be awfully persuasive.",
"A truly rich life contains love and art in abundance.",
"Accept something that you cannot change, and you will feel better.",
"Adventure can be real happiness.",
"Advice, when most needed, is least heeded.",
"All the effort you are making will ultimately pay off.",
"All the troubles you have will pass away very quickly.",
"All will go well with your new project.",
"All your hard work will soon pay off.",
"Allow compassion to guide your decisions.",
"An agreeable romance might begin to take on the appearance.",
"An important person will offer you support.",
"An inch of time is an inch of gold.",
];
